(ns starter.ui
  "Minimal starter application"
  (:require
   [ui.SWT :as ui :refer [application shell label]])  ; clj-kondo can't resolve `label` because it's generated by a macro :-(
  (:import
   [org.eclipse.swt SWT]
   [org.eclipse.swt.layout FillLayout]))

(defn hello
  "Hello, world."
  [& _args]
  (application
   (shell
    "Hello application"

    :layout (FillLayout.)

    (label "Hello, world"))))



(comment
  "How to start a SWT application from the REPL."

  (def app (future (hello)))

  :eoc)
